name: Run Tests

on:
  workflow_call:
    inputs:
      container-image:
        required: true
        type: string
      test-command:
        required: true
        type: string

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: docker run --rm -v "${{ github.workspace }}:/workspace" -e "GITHUB_TOKEN=$GITHUB_TOKEN" -e "GITHUB_ACTOR=$GITHUB_ACTOR" -v "/tmp/npm-cache:/root/.npm" -w /workspace ${{ inputs.container-image }} sh -c "${{ inputs.test-command }}"
